#!/usr/bin/env bash                                                            set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

get_options() {
  if [[ -f "$PHASE_FILE_PATH" ]]; then
    DONE=false
    until $DONE; do
      read line || DONE=true
  
      [[ ! -n "$line" ]] && continue
  
      case "$line" in
        \#*)
          continue
          ;;
        *)
          output="$output $line"
          ;;
      esac
    done < $PHASE_FILE_PATH
  fi
}
