#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Check if application is specified
if [[ $1 == docker-options ]] || [[ $1 == docker-options:* ]]; then
  if [[ -z $2 ]]; then
    echo "You must specify an app name"
    exit 1
  else
    APP="$2"
    DOCKER_OPTIONS_FILE="DOCKER_OPTIONS"
    DOCKER_OPTIONS_FILE_PATH="$DOKKU_ROOT/$APP/$DOCKER_OPTIONS_FILE"

    # Check if app exists with the same name
    if [ ! -d "$DOKKU_ROOT/$APP" ]; then
      echo "App $APP does not exist"
      exit 1
    fi

    [ -f $DOCKER_OPTIONS_FILE_PATH ] || {
      touch $DOCKER_OPTIONS_FILE_PATH
    }
  fi
fi

case "$1" in
  # Display applications docker options
  docker-options)
    APP="$2"

    if [ ! -f $DOCKER_OPTIONS_FILE_PATH ] || [ ! -s $DOCKER_OPTIONS_FILE_PATH ] ; then
      echo "$APP has no docker options"
      exit 1
    fi

    cat $DOCKER_OPTIONS_FILE_PATH
  ;;

  # Add a docker option to application
  docker-options:add)
    if [[ -z $3 ]]; then
      echo "Usage: dokku docker-options:add <app> OPTIONS_STRING"
      echo "Must specify an OPTIONS_STRING to add."
      exit 1
    fi

    OPTIONS_STRING="$3"
    echo "$OPTIONS_STRING" >> $DOCKER_OPTIONS_FILE_PATH
    DOCKER_OPTIONS_TEMP=`cat $DOCKER_OPTIONS_FILE_PATH`
    echo -e "$DOCKER_OPTIONS_TEMP" | sed '/^$/d' | sort -u > $DOCKER_OPTIONS_FILE_PATH
  ;;

  # Remove a docker option from application
  docker-options:remove)
    if [[ -z $3 ]]; then
      echo "Usage: dokku docker-options:remove <app> OPTIONS_STRING"
      echo "Must specify OPTIONS_STRING to remove."
      exit 1
    fi

    OPTIONS_STRING="$3"
    DOCKER_OPTIONS_TEMP=`cat "${DOCKER_OPTIONS_FILE_PATH}"`
    DOCKER_OPTIONS_TEMP=$(echo -e "${DOCKER_OPTIONS_TEMP}" | sed "s#${OPTIONS_STRING}##")
    echo -e "$DOCKER_OPTIONS_TEMP" | sed '/^$/d' | sort -u > $DOCKER_OPTIONS_FILE_PATH
  ;;

  # Display usage help
  help)
    cat && cat<<EOF
    docker-options <app>                            display docker options for an app
    docker-options:add <app> OPTIONS_STRING         add an option string an app
    docker-options:remove <app> OPTIONS_STRING      remove an option string from an app
EOF
  ;;

esac
