#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

STDIN=$(cat)
APP="$1"
DOCKER_OPTIONS_FILE="DOCKER_OPTIONS"
DOCKER_OPTIONS_FILE_PATH="$DOKKU_ROOT/$APP/$DOCKER_OPTIONS_FILE"

output=""
if [[ -f "$DOCKER_OPTIONS_FILE_PATH" ]]; then
  DONE=false
  until $DONE; do
    read line || DONE=true

    [[ ! -n "$line" ]] && continue

    case "$line" in
      \#*)
        continue
        ;;
      *)
        output="$output $line"
        ;;
    esac
  done < $DOCKER_OPTIONS_FILE_PATH
fi

echo "$STDIN$output"
